export const FETCH_MOVIE_DATA_PENDING = "FETCH_MOVIE_DATA_PENDING";
export const FETCH_MOVIE_DATA_COMPLETE = "FETCH_MOVIE_DATA_COMPLETE";
export const FETCH_MOVIE_DATA_FAILED = "FETCH_MOVIE_DATA_FAILED";
